### ISSUE TITLE
touchegg crashes with awesome wm

### ISSUE THREAD

**Issue by ArchXUser** [JoseExposito/touchegg#352] opened 2020-10-06 03:46 UTC
I use the SEND_KEYS configuration. It crashes only on clean desktop when there aren't running apps.
Here is the crash log:

Gesture begin detected
	Gesture information:
		Fingers: 4
		Type: SWIPE
		Direction: LEFT
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x0
  Serial number of failed request:  61
  Current serial number in output stream:  61

I use Arch Linux with awesome v4.3 and Xorg 1.20.9-2

**Comment by JoseExposito** [comment] 2020-10-07 18:05
Hi!

Thanks a lot for the bug report, it was really useful. Your problems should be fixed now :smile: 

Since you are on Arch, could you confirm that the problem is solved ny installing `touchegg-git` from AUR?
I'll reopen the issue in case you have any other problem.

Jose

**Comment by ArchXUser** [comment] 2020-10-08 01:26
Hi, it wasn't help me. Also I have this issue with other actions like close a window, send_keys, execute a command, minimize a window (others not work with awesomewm). Maybe is it connected with window-system?

xprop output the desktop:

`XFree86_DDC_EDID1_RAWDATA(INTEGER) = 0, -1, -1, -1, -1, -1, -1, 0, 9, -27, 25, 8, 0, 0, 0, 0, 32, 28, 1, 4, -107, 34, 19, 120, 2, -55, -96, -107, 93, 89, -111, 41, 31, 80, 84, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 26, 59, -128, 36, 113, 56, 60, 64, 48, 32, 54, 0, 88, -62, 16, 0, 0, 26, 72, 47, -128, 36, 113, 56, 60, 64, 48, 32, 54, 0, 88, -62, 16, 0, 0, 26, 0, 0, 0, -2, 0, 84, 49, 87, 68, 51, -128, 78, 86, 49, 53, 78, 51, 68, 0, 0, 0, 0, 0, 0, 65, 33, -106, 0, 16, 0, 0, 10, 1, 10, 32, 32, 0, 66
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x0
_NET_CLIENT_LIST(WINDOW): window id # 0x3800002, 0x2200003
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x3800002, 0x2200003
_NET_CURRENT_DESKTOP(CARDINAL) = 2
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 5
_NET_DESKTOP_NAMES(UTF8_STRING) = "1", "2", "3", "4", "5"
AT_SPI_BUS(STRING) = "unix:abstract=/tmp/dbus-djZbMPSXfj,guid=92d36ac5a5c485ef831dcff25f7e6203"
XAUTOLOCK_SEMAPHORE_PID(INTEGER) = 70, 6, 0, 0
_MIT_SCREEN_SAVER_ID(PIXMAP): pixmap id # 0x800000
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x400005
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_SUPPORTING_WM_CHECK, _NET_STARTUP_ID, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_NUMBER_OF_DESKTOPS, _NET_CURRENT_DESKTOP, _NET_DESKTOP_NAMES, _NET_ACTIVE_WINDOW, _NET_CLOSE_WINDOW, _NET_FRAME_EXTENTS, _NET_WM_NAME, _NET_WM_STRUT_PARTIAL, _NET_WM_ICON_NAME, _NET_WM_VISIBLE_ICON_NAME, _NET_WM_DESKTOP, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU, _NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_COMBO, _NET_WM_WINDOW_TYPE_DND, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_ICON, _NET_WM_PID, _NET_WM_STATE, _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_MODAL, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_DEMANDS_ATTENTION
RESOURCE_MANAGER(STRING) = "Xft.dpi:\t120\n"
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x600000
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x600000
GDK_VISUALS(INTEGER) = 1422, 1924
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us,ru", "-option", "grp:alt_shift_toggle,grp_led:scroll,terminate:ctrl_alt_bksp,grp:alt_shift_toggle,grp_led:scroll,terminate:ctrl_alt_bksp"
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 7
Xorg_Seat(STRING) = "seat0"`

**Comment by JoseExposito** [comment] 2020-10-10 14:45
Thanks for the command output, I was going to ask for that very command hehehe

I looks like you don't have a desktop window (with icons, folders, etc), instead, Awesome WM is using the root window as desktop. That is weird, because even if I force to perform a gesture on my root window Touchégg doesn't crash.

Could you close every window with the exception of the terminal and paste the output of this command please?

```
$ xwininfo -tree -root
```

Let's see why it crashes... BTW, do you feel confortable compiling C++? I believe I know how to fix it, but I'll need you to test the patch.

**Comment by ArchXUser** [comment] 2020-10-11 02:18
> BTW, do you feel confortable compiling C++?

Yes

without backgrounds programs.
```
$ xwininfo -tree -root
xwininfo: Window id: 0x79b (the root window) (has no name)

  Root window id: 0x79b (the root window) (has no name)
  Parent window id: 0x0 (none)
     11 children:
     0x400006 "Awesome systray window": ("awesome" "awesome")  20x20+-512+-512  +-512+-512
     0x1e00000 (has no name): ()  1x1+0+0  +0+0
     0x1c00000 (has no name): ()  1x1+0+0  +0+0
     0x1a00000 (has no name): ()  1x1+0+0  +0+0
     0x1800000 (has no name): ()  1x1+0+0  +0+0
     0x400089 (has no name): ()  1920x1060+0+20  +0+20
        1 child:
        0x600002 "Alacritty": ("Alacritty" "Alacritty")  1920x1060+0+0  +0+20
     0x400012 "Awesome drawin": ("awesome" "awesome")  1920x20+0+0  +0+0
     0x40000d "Awesome drawin": ("awesome" "awesome")  175x240+0+0  +0+0
     0x400007 "Awesome no input window": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
     0x400005 "awesome": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
     0x400004 "Awesome WM_Sn selection owner window": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
```

with backgrounds programs.
```
$ xwininfo -tree -root
xwininfo: Window id: 0x79b (the root window) (has no name)

  Root window id: 0x79b (the root window) (has no name)
  Parent window id: 0x0 (none)
     17 children:
     0x1000000 (has no name): ()  1x1+0+0  +0+0
     0xe00000 (has no name): ()  1x1+0+0  +0+0
     0xa00000 (has no name): ()  1x1+0+0  +0+0
     0x800000 (has no name): ()  1x1+0+0  +0+0
     0x40002e "Awesome drawin": ("awesome" "awesome")  228x56+1685+25  +1685+25
     0x400079 (has no name): ()  1920x1060+0+20  +0+20
        1 child:
        0x600002 "Alacritty": ("Alacritty" "Alacritty")  1920x1060+0+0  +0+20
     0x400012 "Awesome drawin": ("awesome" "awesome")  1920x20+0+0  +0+0
        1 child:
        0x400006 "Awesome systray window": ("awesome" "awesome")  20x20+1483+0  +1483+0
           1 child:
           0x2e00010 "xfce4-power-manager": ("xfce4-power-manager" "Xfce4-power-manager")  20x20+0+0  +1483+0
              1 child:
              0x2e00011 (has no name): ()  1x1+-1+-1  +1482+-1
     0x40000d "Awesome drawin": ("awesome" "awesome")  175x240+0+0  +0+0
     0x400007 "Awesome no input window": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
     0x400005 "awesome": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
     0x400004 "Awesome WM_Sn selection owner window": ("awesome" "awesome")  1x1+-1+-1  +-1+-1
     0x2e00009 (has no name): ()  1x1+-1+-1  +-1+-1
     0x2600001 "pulseeffects": ("pulseeffects" "Pulseeffects")  10x10+10+10  +10+10
     0x2c00001 "polkit-gnome-authentication-agent-1": ("polkit-gnome-authentication-agent-1" "Polkit-gnome-authentication-agent-1")  10x10+10+10  +10+10
     0x2e00001 "xfce4-power-manager": ("xfce4-power-manager" "Xfce4-power-manager")  10x10+10+10  +10+10
     0x2800004 "picom": ("picom" "picom")  1x1+0+0  +0+0
     0x2a00001 "xautolock": ("xautolock" "Xautolock")  1x1+-1+-1  +-1+-1
```

**Comment by JoseExposito** [comment] 2020-10-11 10:20
I finally installed awesome WM and it is not crashing anymore :smiley: 

Let me know if you find any other issue.
Jose

**Closed by JoseExposito** 2020-10-11 10:20 UTC
Labels: Priority-Medium, bug
