### ISSUE TITLE
Window flickers when maximizing or restoring a window

### ISSUE THREAD

**Issue by spikespaz** [JoseExposito/touchegg#554] opened 2022-01-01 09:08 UTC
### Describe the bug

```xml
    <gesture type="SWIPE" fingers="3" direction="UP">
      <action type="MAXIMIZE_RESTORE_WINDOW"></action>
    </gesture>
```

Causes the window to flicker/teleport around the screen before assuming the proper size.
Issue is on Cinnamon.

https://user-images.githubusercontent.com/12502988/147847675-d01710d5-f590-4873-bf03-ecab79236d42.mp4

### Expected behaviour

In the video as shown, the correct behavior is a smooth scale of the window edges to the edges of the desktop boundary.

### Your environment

 * Version of Touchégg: Touchégg v2.0.12.

<pre><font color="#4E9A06"><b>██████████████████  ████████</b></font>   <font color="#4E9A06"><b>jacob</b></font>@<font color="#4E9A06"><b>jacob-thinkpad</b></font> 
<font color="#4E9A06"><b>██████████████████  ████████</b></font>   -------------------- 
<font color="#4E9A06"><b>██████████████████  ████████</b></font>   <font color="#4E9A06"><b>OS</b></font>: Manjaro Linux x86_64 
<font color="#4E9A06"><b>██████████████████  ████████</b></font>   <font color="#4E9A06"><b>Host</b></font>: 20Y1S00C00 ThinkPad P14s Gen 1 
<font color="#4E9A06"><b>████████            ████████</b></font>   <font color="#4E9A06"><b>Kernel</b></font>: 5.15.7-1-MANJARO 
<font color="#4E9A06"><b>████████  ████████  ████████</b></font>   <font color="#4E9A06"><b>Uptime</b></font>: 7 hours, 43 mins 
<font color="#4E9A06"><b>████████  ████████  ████████</b></font>   <font color="#4E9A06"><b>Packages</b></font>: 1387 (pacman), 17 (snap) 
<font color="#4E9A06"><b>████████  ████████  ████████</b></font>   <font color="#4E9A06"><b>Shell</b></font>: zsh 5.8 
<font color="#4E9A06"><b>████████  ████████  ████████</b></font>   <font color="#4E9A06"><b>Resolution</b></font>: 1920x1080 
<font color="#4E9A06"><b>████████  ████████  ████████</b></font>   <font color="#4E9A06"><b>DE</b></font>: Cinnamon 5.0.7 
<font color="#4E9A06"><b>████████  ████████  ████████</b></font>   <font color="#4E9A06"><b>WM</b></font>: Mutter (Muffin) 
<font color="#4E9A06"><b>████████  ████████  ████████</b></font>   <font color="#4E9A06"><b>WM Theme</b></font>: Mint-Y-Dark-Aqua (Adapta-Maia) 
<font color="#4E9A06"><b>████████  ████████  ████████</b></font>   <font color="#4E9A06"><b>Theme</b></font>: Mint-Y-Dark-Aqua [GTK2/3] 
<font color="#4E9A06"><b>████████  ████████  ████████</b></font>   <font color="#4E9A06"><b>Icons</b></font>: Papirus-Dark-Maia [GTK2/3] 
                               <font color="#4E9A06"><b>Terminal</b></font>: gnome-terminal 
                               <font color="#4E9A06"><b>CPU</b></font>: AMD Ryzen 7 PRO 4750U with Radeon Graphics (16) @ 1.700GHz 
                               <font color="#4E9A06"><b>GPU</b></font>: AMD ATI 07:00.0 Renoir 
                               <font color="#4E9A06"><b>Memory</b></font>: 5767MiB / 21809MiB 
</pre>

**Comment by JoseExposito** [comment] 2022-01-01 11:26
It could be a problem with your window manager. Under the hood, Touchégg does something similar to this command:

```
$ wmctrl -r :ACTIVE: -b toggle,maximized_vert,maximized_horz
```

Does the same happen when running it?

**Comment by spikespaz** [comment] 2022-01-01 13:05
`wmctrl` is not an executable for me, if it should be installed. But yes, it does the same thing. Do you have an idea for a workaround?

**Comment by spikespaz** [comment] 2022-01-01 13:20
Another question, but I don't want to open another issue. Why does it sometimes insert text/press buttons (and mess up what I'm working on in VS Code) when it isn't even using keybinds?

**Comment by JoseExposito** [comment] 2022-01-01 16:29
> wmctrl is not an executable for me, if it should be installed. But yes, it does the same thing. Do you have an idea for a workaround?

If `wmctrl` is causing the same issue, then the problem is most likely in Mutter. You can try to report the bug in their [issue tracker](https://gitlab.gnome.org/GNOME/mutter). The `wmctrl` command should be enough for them to test it. 

Since you are using Cinnamon, the issue could be on their side, it's difficult to tell without testing in both DEs.

> Another question, but I don't want to open another issue. Why does it sometimes insert text/press buttons (and mess up what I'm working on in VS Code) when it isn't even using keybinds?
>
> Edit: It seems to be pasting text in Chrome too however in Code it also adds cursors and whatnot sometimes.

Maybe you are tapping with 3 fingers unintentionally? A 3 fingers tap behaves like a mouse wheel click and its default action is to copy/paste text.

Closing the issue because the bug is somewhere else, but feel free to add more comments if required.

**Closed by JoseExposito** 2022-01-01 16:29 UTC

**Comment by spikespaz** [comment] 2022-01-02 05:39
I believe it is because of the order that libinput sends events. If a swipe gesture is recognized, a tap event should be ignored.

I am not tapping, it is a light "flick" however. I can assure you that my fingers travel a significant distance and stay in contact with the surface the whole time, and the issue here is the speed at which I perform the gesture. Just like using a Windows Precision or Mac touchpad.

https://gitlab.freedesktop.org/libinput/libinput/-/issues/720

**Comment by JoseExposito** [comment] 2022-01-03 16:59
Looking into the issue there, I'm also a contributor :)

**Comment by spikespaz** [comment] 2022-01-04 01:50
That's why I posted it here :smile:
