### ISSUE TITLE
Add switch / option to check config file.

### ISSUE THREAD

**Issue by undrwater** [JoseExposito/touchegg#359] opened 2020-10-14 20:00 UTC
I recently edited my config file, and treid to restart touchegg:

>Starting Touchégg in client mode
Parsing you configuration file...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error parsing configuration file

I don't know where the error in the configuration file is. Perhaps a --test switch or option to test the config would be useful?
Here's what I added:

```
<application name="ALL">
    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="SEND_KEYS">
        <modifiers>Alt_L</modifiers>
        <keys>leftarrow</keys>
      </action>
    </gesture>
```

**Comment by JoseExposito** [comment] 2020-10-15 06:31
Thank you very much for your report.

Your SEND_KEYS action seems to be fine. Copy and paste here your full configuration so I can help you to fix it.

It is true that the error is too generic, however, I'm working on a GUI to easily edit your configuration, so you won't have this issues in the future, so I adding a "test" option is not in my roadmap.

**Comment by undrwater** [comment] 2020-10-15 16:50
Here's the config:




[touchegg.conf.txt](https://github.com/JoseExposito/touchegg/files/5386511/touchegg.conf.txt)

It's hard to copy the text here. So much of it gets parsed. Paste just in case:
https://dpaste.com/9BAUKENEA

**Comment by JoseExposito** [comment] 2020-10-17 08:04
Hi!

The problem is the extra block you added at the end of the file:

```xml
  <application name="chromium-browser-chromium">
    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="SEND_KEYS">
        <modifiers>Alt_L</modifiers>
        <keys>leftarrow</keys>
      </action>
    </gesture>
```
It is missing the closing `</application>` tag:

```xml
  <application name="chromium-browser-chromium">
    <gesture type="SWIPE" fingers="3" direction="LEFT">
      <action type="SEND_KEYS">
        <modifiers>Alt_L</modifiers>
        <keys>leftarrow</keys>
      </action>
    </gesture>
  </application>
```

I'm not sure if `chromium-browser-chromium` is the right name, in my computer it is `Chromium-browser`, but it may be different in yours.

**Closed by JoseExposito** 2020-10-17 08:04 UTC
