### ISSUE TITLE
Swipe up with three fingers sometimes it's buggy 

### ISSUE THREAD

**Issue by jawadalkassim** [JoseExposito/touchegg#549] opened 2021-11-07 12:32 UTC
### Describe the bug
Sometimes when swiping up with three finger to show Workspaces it's keep going back to desktop and never get the Gesture complete 

https://imgur.com/a/8vTKetY

### Expected behaviour
Smoothly open Workspaces

### Actual behaviour
Can't access Workspaces  and keep reverting to Desktop

### Your environment

 * Version of Touchégg: Touchégg v2.0.12 Copr
 * Operating System: Fedora 35
 * Desktop Environment: Gnome 41.1

**Comment by jawadalkassim** [comment] 2021-11-07 12:37
it's fixed after restart or log out  but it's keep happening again

**Comment by marcosonoio** [comment] 2021-11-07 17:46
I have this problem too, on KDE Neon.
I found some strange values:
`journalctl -u touchegg -b -f
-- Logs begin at Sun 2021-11-07 18:42:17 CET. --
nov 07 18:44:29 ThinkPad-T460s touchegg[14627]: Creating D-Bus server
nov 07 18:44:29 ThinkPad-T460s touchegg[14627]: Server started at address unix:abstract=touchegg
nov 07 18:44:29 ThinkPad-T460s touchegg[14627]: A list of detected compatible devices will be displayed below:
nov 07 18:44:30 ThinkPad-T460s touchegg[14627]: Compatible device detected:
nov 07 18:44:30 ThinkPad-T460s touchegg[14627]:         Name: SynPS/2 Synaptics TouchPad
nov 07 18:44:30 ThinkPad-T460s touchegg[14627]:         Size: 100.25mm x 57.5231mm
nov 07 18:44:30 ThinkPad-T460s touchegg[14627]:         Calculating start_threshold and finish_threshold. You can tune this values in your service file
nov 07 18:44:30 ThinkPad-T460s touchegg[14627]:         start_threshold: 113.234
nov 07 18:44:30 ThinkPad-T460s touchegg[14627]:         finish_threshold_horizontal: 1578.74
nov 07 18:44:30 ThinkPad-T460s touchegg[14627]:         finish_threshold_vertical: 905.875
nov 07 18:44:34 ThinkPad-T460s touchegg[14627]: New client connection request
nov 07 18:44:34 ThinkPad-T460s touchegg[14627]: New client connected
`

**Comment by JoseExposito** [comment] 2021-11-08 17:29
@jawadalkassim could you confirm if the issue is similar to https://github.com/JoseExposito/touchegg/issues/542, please?

If not, could you attach the output of `touchegg --debug` and `libinput --version`, please?

**Comment by jawadalkassim** [comment] 2021-11-08 20:04
@JoseExposito  Also Happening in Fedora 35
``` ~> touchegg --debug
Touchégg v2.0.12.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/jawad/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: Alacritty
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: DOWN
	Gesture performed on app:
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: Alacritty
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: PINCH
		Direction: IN
	Gesture performed on app:
	Action configured for this gesture
	Starting action
Gesture update detected (0.499657%)
Gesture update detected (0.845211%)
Gesture update detected (1.18677%)
Gesture update detected (1.35858%)
Gesture update detected (1.33424%)
Gesture update detected (1.54743%)
Gesture update detected (2.06935%)
Gesture update detected (2.58882%)
Gesture update detected (2.88009%)
Gesture update detected (2.69675%)
Gesture update detected (2.4235%)
Gesture update detected (2.45796%)
Gesture update detected (2.69525%)
Gesture update detected (2.36706%)
Gesture update detected (2.45289%)
Gesture update detected (1.83897%)
Gesture update detected (1.16019%)
Gesture update detected (1.11323%)
Gesture update detected (1.25877%)
Gesture update detected (1.3883%)
Gesture update detected (1.66818%)
Gesture update detected (1.58037%)
Gesture update detected (1.3315%)
Gesture update detected (1.28302%)
Gesture update detected (1.4435%)
Gesture update detected (2.1451%)
Gesture update detected (3.24601%)
Gesture update detected (3.0501%)
Gesture end detected
```


`~> libinput --version
1.19.2`

**Comment by JoseExposito** [comment] 2021-11-09 18:18
Do you see a message similar to this one when running...

```
$ journalctl -u touchegg -b
[...]
It wasn't possible to get your device physical size, falling back to default start_threshold and finish_threshold. You can tune this values in your service file:
https://github.com/JoseExposito/touchegg#daemon-configuration
```

You might need to configure the thresholds manually as explained here:
https://github.com/JoseExposito/touchegg#daemon-configuration

**Comment by jawadalkassim** [comment] 2021-11-27 00:25
@JoseExposito i'm sorry for late respond
```
jawad@fedora ~ [SIGINT]> journalctl -u touchegg -b
-- Journal begins at Sun 2021-11-07 20:20:31 EET, ends at Sat 2021-11-27 02:24:32 EET. --
Nov 27 02:23:06 fedora systemd[1]: Started Touchégg Daemon.
Nov 27 02:23:06 fedora touchegg[24923]: Touchégg v2.0.12.
Nov 27 02:23:06 fedora touchegg[24923]: Starting Touchégg in daemon mode
Nov 27 02:23:06 fedora touchegg[24923]: Starting daemon server...
Nov 27 02:23:06 fedora touchegg[24923]: Generating D-Bus introspection data
Nov 27 02:23:06 fedora touchegg[24923]: Creating D-Bus server
Nov 27 02:23:06 fedora touchegg[24923]: Server started at address unix:abstract=touchegg
Nov 27 02:23:06 fedora touchegg[24923]: A list of detected compatible devices will be displayed below:
Nov 27 02:23:09 fedora touchegg[24923]: Compatible device detected:
Nov 27 02:23:09 fedora touchegg[24923]:         Name: DELL0810:00 04F3:30C4 Touchpad
Nov 27 02:23:09 fedora touchegg[24923]:         Size: 103.71mm x 78.3548mm
Nov 27 02:23:09 fedora touchegg[24923]:         Calculating start_threshold and finish_threshold. You can tune this val>
Nov 27 02:23:09 fedora touchegg[24923]:         start_threshold: 30.8484
Nov 27 02:23:09 fedora touchegg[24923]:         finish_threshold_horizontal: 367.475
Nov 27 02:23:09 fedora touchegg[24923]:         finish_threshold_vertical: 277.635
Nov 27 02:23:09 fedora touchegg[24923]: New client connection request
Nov 27 02:23:09 fedora touchegg[24923]: New client connected
Nov 27 02:24:26 fedora touchegg[24923]: New client connection request
Nov 27 02:24:26 fedora touchegg[24923]: New client connected
Nov 27 02:24:27 fedora touchegg[24923]: Client disconnected
```

**Comment by jawadalkassim** [comment] 2021-11-27 00:37
> You might need to configure the thresholds manually as explained here:
> https://github.com/JoseExposito/touchegg#daemon-configuration

I've tried doing this but the it's still happening, i was able to replicate this after lock the screen and then log in

**Comment by JoseExposito** [comment] 2021-11-29 08:09
libinput version and Touchégg versions are fine.

> I've tried doing this but the it's still happening, i was able to replicate this after lock the screen and then log in

Ok, I didn't understand this bit from your original report. So, if I understood it correctly, after a fresh reboot, everything works fine, but when you lock the screen and log in, the bug shows up. Is that correct?

If this is the case, could you attach the output of:

 - After a fresh boot:
   - journalctl -u touchegg -b
   - touchegg --debug
 - After lock/log in:
   - journalctl -u touchegg -b
   - touchegg --debug

Let's see what changes...

**Comment by jawadalkassim** [comment] 2021-11-29 11:07
**After  a Fresh Boot**
```
jawad@fedora ~> journalctl -u touchegg -b
-- Journal begins at Sun 2021-11-07 20:20:31 EET, ends at Mon 2021-11-29 12:56:22 EET. --
Nov 29 12:56:03 fedora systemd[1]: Started Touchégg Daemon.
Nov 29 12:56:04 fedora touchegg[835]: Touchégg v2.0.12.
Nov 29 12:56:04 fedora touchegg[835]: Starting Touchégg in daemon mode
Nov 29 12:56:04 fedora touchegg[835]: Starting daemon server...
Nov 29 12:56:04 fedora touchegg[835]: Generating D-Bus introspection data
Nov 29 12:56:04 fedora touchegg[835]: Creating D-Bus server
Nov 29 12:56:04 fedora touchegg[835]: Server started at address unix:abstract=touchegg
Nov 29 12:56:04 fedora touchegg[835]: A list of detected compatible devices will be displayed below:
Nov 29 12:56:04 fedora touchegg[835]: Compatible device detected:
Nov 29 12:56:04 fedora touchegg[835]:         Name: DELL0810:00 04F3:30C4 Touchpad
Nov 29 12:56:04 fedora touchegg[835]:         Size: 103.71mm x 78.3548mm
Nov 29 12:56:04 fedora touchegg[835]:         Calculating start_threshold and finish_threshold. You can tune this value>
Nov 29 12:56:04 fedora touchegg[835]:         start_threshold: 30.8484
Nov 29 12:56:04 fedora touchegg[835]:         finish_threshold_horizontal: 367.475
Nov 29 12:56:04 fedora touchegg[835]:         finish_threshold_vertical: 277.635
Nov 29 12:56:13 fedora touchegg[835]: New client connection request
Nov 29 12:56:13 fedora touchegg[835]: New client connected
Nov 29 12:56:14 fedora touchegg[835]: New client connection request
Nov 29 12:56:14 fedora touchegg[835]: New client connected
```

```
jawad@fedora ~> touchegg --debug
Touchégg v2.0.12.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/jawad/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: Alacritty
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: DOWN
	Gesture performed on app:
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: Alacritty
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
```

**After Lock screen and unlock it again:**
Lock Screen With Super + L in Gnome
or Super + Esc in Pop_OS

```
jawad@fedora ~ [SIGINT]> journalctl -u touchegg -b
-- Journal begins at Sun 2021-11-07 20:20:31 EET, ends at Mon 2021-11-29 12:57:41 EET. --
Nov 29 12:56:03 fedora systemd[1]: Started Touchégg Daemon.
Nov 29 12:56:04 fedora touchegg[835]: Touchégg v2.0.12.
Nov 29 12:56:04 fedora touchegg[835]: Starting Touchégg in daemon mode
Nov 29 12:56:04 fedora touchegg[835]: Starting daemon server...
Nov 29 12:56:04 fedora touchegg[835]: Generating D-Bus introspection data
Nov 29 12:56:04 fedora touchegg[835]: Creating D-Bus server
Nov 29 12:56:04 fedora touchegg[835]: Server started at address unix:abstract=touchegg
Nov 29 12:56:04 fedora touchegg[835]: A list of detected compatible devices will be displayed below:
Nov 29 12:56:04 fedora touchegg[835]: Compatible device detected:
Nov 29 12:56:04 fedora touchegg[835]:         Name: DELL0810:00 04F3:30C4 Touchpad
Nov 29 12:56:04 fedora touchegg[835]:         Size: 103.71mm x 78.3548mm
Nov 29 12:56:04 fedora touchegg[835]:         Calculating start_threshold and finish_threshold. You can tune this value>
Nov 29 12:56:04 fedora touchegg[835]:         start_threshold: 30.8484
Nov 29 12:56:04 fedora touchegg[835]:         finish_threshold_horizontal: 367.475
Nov 29 12:56:04 fedora touchegg[835]:         finish_threshold_vertical: 277.635
Nov 29 12:56:13 fedora touchegg[835]: New client connection request
Nov 29 12:56:13 fedora touchegg[835]: New client connected
Nov 29 12:56:14 fedora touchegg[835]: New client connection request
Nov 29 12:56:14 fedora touchegg[835]: New client connected
Nov 29 12:56:50 fedora touchegg[835]: New client connection request
Nov 29 12:56:50 fedora touchegg[835]: New client connected
Nov 29 12:57:26 fedora touchegg[835]: Client disconnected
Nov 29 12:57:41 fedora touchegg[835]: New client connection request
Nov 29 12:57:41 fedora touchegg[835]: New client connected

```

```
jawad@fedora ~> touchegg --debug
Touchégg v2.0.12.
Starting Touchégg in client mode
Parsing your configuration file...
Using configuration file "/home/jawad/.config/touchegg/touchegg.conf"
Configuration parsed successfully
Connecting to Touchégg daemon...
Connection with Touchégg established
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: Alacritty
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)
Gesture begin detected
	Gesture information:
		Fingers: 3
		Type: SWIPE
		Direction: UP
	Gesture performed on app: Alacritty
	Action configured for this gesture
	Ignoring this gesture. This could mean no action is configured, the configured action is not supported or that it was performed in a system window (panel, dock, desktop, etc)

```
i got this error one time i don't if it's relevant:
```
Nov 29 12:30:16 fedora touchegg[4319]: libinput error: event7  - DELL0810:00 04F3:30C4 Touchpad: libinput bug: tp_gesture_end in unknown gesture mode
```

**Comment by jawadalkassim** [comment] 2021-11-29 22:44
```
jawad@fedora ~> journalctl -u touchegg -b -f
-- Journal begins at Sun 2021-11-07 20:20:31 EET. --
Nov 30 00:05:30 fedora touchegg[12555]: New client connected
Nov 30 00:05:33 fedora touchegg[12555]: New client connection request
Nov 30 00:05:33 fedora touchegg[12555]: New client connected
Nov 30 00:17:15 fedora touchegg[12555]: libinput error: event7  - DELL0810:00 04F3:30C4 Touchpad: libinput bug: tp_gesture_end in unknown gesture mode
Nov 30 00:24:40 fedora touchegg[12555]: libinput error: event7  - DELL0810:00 04F3:30C4 Touchpad: kernel bug: Touch jump detected and discarded.
Nov 30 00:24:40 fedora touchegg[12555]: See https://wayland.freedesktop.org/libinput/doc/1.19.2/touchpad-jumping-cursors.html for details
Nov 30 00:33:55 fedora touchegg[12555]: New client connection request
Nov 30 00:33:55 fedora touchegg[12555]: New client connected
Nov 30 00:34:31 fedora touchegg[12555]: Client disconnected
Nov 30 00:43:01 fedora touchegg[12555]: libinput error: event7  - DELL0810:00 04F3:30C4 Touchpad: libinput bug: tp_gesture_end in unknown gesture mode

```

**Comment by JoseExposito** [comment] 2021-11-30 09:42
Thanks a lot for the logs @jawadalkassim. The problem doesn't seem to be in Touchégg, it is most likely in [X11 Gestures](https://github.com/JoseExposito/gnome-shell-extension-x11gestures).

I didn't manage to reproduce it, after lock/log in I'm still able to open the overview view, but I see some errors in my journal. Hopefully fixing those your error should be fixed as well. I'll have a fix available tomorrow. I'll drop you a message just in case you can test it and confirm than the problem is solved.

> Touchpad: libinput bug: tp_gesture_end in unknown gesture mode

That's a bug on libinput. I already fixed it, but it's not released yet:
https://gitlab.freedesktop.org/libinput/libinput/-/commit/5e44861e0ed7fdb447170a03adb9ff361ae6e4ce

**Comment by jawadalkassim** [comment] 2021-11-30 13:44
@JoseExposito OK sounds good, i hope it will be solved, I'm ready to test jut let me know.
i have also  noticed something when i swipe up fast to the top of the touchpad it cause the problem too.
just when i swipe slowly and not much it works.
in fresh boot i can swipe fast and to end of touchpad and still got the gesture to work and the overview open normally
but when the issue occurs only slowly moving will work. and just maybe half of the touchpad size and any movement of my finger more than that it will revert to desktop

**Comment by jawadalkassim** [comment] 2021-11-30 17:26
@JoseExposito  
https://github.com/JoseExposito/touchegg/issues/549#issue-1046735348
i think it's the same issue

**Comment by JoseExposito** [comment] 2021-12-01 07:09
Yes, I think so. See my comment there:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/issues/30#issuecomment-983352399

I attached a new version of the extension (hopefully) including the fix. Let me know if that worked for you.

**Closed** 2021-12-01 12:55 UTC

**Comment by JoseExposito** [comment] 2021-12-01 13:07
Cool! Thanks for testing it, I'll release a new version ASAP with the fix

**Comment by jawadalkassim** [comment] 2021-12-01 13:14
@JoseExposito should i remove the extracted extension file and re-installing it from gnome extensions to get later updates?

**Comment by JoseExposito** [comment] 2021-12-02 11:28
Just send for review the latest version:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/releases/tag/13

To be honest, I'm not sure if removing it is required, just in case do it, you'll receive the update as soon as the review process finish. It usually takes a couple of days.

**Comment by jawadalkassim** [comment] 2021-12-02 14:35
@JoseExposito that's fast , updated successfully throw GNOME extensions App, without deleting old files 👏👏👏👏❤️❤️
Thank you
